### ISSUE TITLE
[M1] Appendix B - Data Dictionary

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#21]
Data dictionary is used to track all the different variables, states and functional requirements that you described in your document. The purpose of the Data dictionary is to layout the definition of terms used in this document and align the readers to the authors perspectives.

Make sure to include the complete list of all constants, state variables (and their possible states), inputs and outputs in a table. In the table, include the description of these items as well as all related operations and requirements.

Term 1
List the definition of term 1 here. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis purus ex, hendrerit sed mi consequat, dignissim lobortis velit.

Term 2
List the definition of term 2 here. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis purus ex, hendrerit sed mi consequat, dignissim lobortis velit.

Term 3
List the definition of term 3 here.

**Comment by genaaaaa** [comment]
ExpressJS
Express.js is a back end web application framework, designed for building web applications and RESTful APIs with Node.js. It is released as free and open-source software under the MIT License. 
AES256
256-bit AES encryption is a technique that uses a key length of 256 bits for this process. The AES-256 key has the mathematical equivalent of 2256 potential combinations because key combinations increase exponentially with key size. Using 256-bit AES encryption assures the security of your data at rest.
2FA
Two-factor authentication (2FA) is a security mechanism for identity and access management that requires two forms of identification to access services and data. 
MFA
Multi-factor authentication is a type of electronic authentication in which a user is only permitted access to a website or application after successfully providing two or more pieces of evidence to an authentication mechanism.
SSL
Secure Sockets Layer (SSL), is an encryption-based Internet security protocol. It was first developed by Netscape in 1995  to ensure privacy, authentication, and data integrity in Internet communications. SSL is the predecessor to the modern TLS encryption used today.
Denial of Service
Denial of service (DoS) is a type of cyber attack that aims to disable, shut down or disrupt a network, website or service. 
PF
Product Functionality (PR) is the functions that the product must perform or must let the user perform.
FR
Functional Requirements (FR) captures the intended behaviour of the system. This behavior may be expressed as services, tasks or functions the system is required to perform.
NFR
Non-functional Requirements (FR) includes generic properties of the system that focuses on system usability.
