### ISSUE TITLE
[M2] Iphigena's Task Reflections

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#45]
Each member is required to write no more than 2 paragraphs of what they have done for milestone one, what they have learned, how they were to do it differently if they are given another chance to do it again, and as a team what can be done better.

**Comment by genaaaaa** [comment]
For milestone two (M2), I was in charge of ensuring everyone communicated with each other to clarify doubts and align opinions. Additionally, I have contributed to finishing the report, specific requirements, sequence diagrams, and improving certain sections such as the scope and use case descriptions based on M1 feedback. I have gained a better understanding of Architectural and Design Patterns while doing M2 and was able to differentiate the architecture and design patterns better. 

If given another chance, I believe that the team could arrange a consultation session earlier with the professor to clarify the doubts we have regarding M2. It would be more beneficial to the team as we would then be able to express our issues in a clear and concise manner compared to asking questions via email. Moreover, as a team, I feel that we have done a great job improving on our communication as compared to M1. In addition, I suggest that we can still work on asking better phrased questions among ourselves to avoid wasting time due to misinterpretations.
