### ISSUE TITLE
[M3] Prototype (Manager)

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#55]
Manager's prototype pages include the dashboard and job allocation pages

Dashboard Page

- Manager to see staff workload on the landing page (top three staff with lowest workload should be shown, and highlight all staff with over 40 hours of job allocated)

Job Allocation Page

- Allow managers to allocate jobs to staff one week at a time and view staff availability (up to 3?) and relevant information on job allocation page

Availability includes workload assigned, staff's job preference, staff's location at a particular date and availabilities for the week.

Things to note:

Staff can only teach up to 4 hours at one time. They must have at least an hour break before
then can proceed with another 4 hours block.

At all times, only one staff can be using a studio

Opening hours are Monday to Friday 9 am to 9 pm and on the weekends 8 am to 9 pm. The school is closed on all public holidays.

**Comment by genaaaaa** [comment]
Manager 
The following wireframes will demonstrate the use cases UC1-4: View Staff Workload, Staff Availability, Allocate Job and Reallocate Job. 

Dashboard Page

The Manager Dashboard Page, as shown in Figure 6. is displayed after the manager has logged in. The manager will be able to visualise the staff workload, top three staff with the lowest workload and all staff over 40 hours of jobs allocated are highlighted in red. Additionally, the overall instrument workload is known to the manager so that better arrangement could be made to allocate staff accordingly. 


Figure 6: Manager Dashboard Page


Job Allocation Page
The Manager Job Allocation Page, as shown in Figure 7, is displayed after the manager chooses to allocate jobs. The manager will be able to allocate jobs to staff for one week at a time, view up to three staff availability and any relevant information. When displaying the staff availability, the workload assigned, staff’s job preference, staff’s location at a particular date, and availability for the week are shown to the manager.

After viewing the staff availability, the manager can select the type of lesson, date and time slots. The system will then fetch available studio and staff and a dropdown list of studio and staff will be shown to the manager. After the manager selects the studio and the staff, they will be able to submit the information. A green confirmation message “Job Allocated Successfully” will be displayed after the system added the job into the database.



Figure 7: Manager Job Allocation Page

Job Reallocation Page
The Manager Job Reallocation Page, as shown in Figure 8. is displayed after the manager  chooses to reallocate the rejected job(s). The manager will be able to select which job to reallocate. The manager will be able to view staff availability and any relevant information. When displaying the staff availability, the workload assigned, staff’s job preference, staff’s location at a particular date, and availability for the week are shown to the manager.

After viewing the staff availability, the manager can allocate the job based on staff availability. After the manager submits the information, a green confirmation message “Job Reallocated Successfully” will be displayed when the system updates the job in the database. 


Figure 8: Manager Job Reallocation Page
