### ISSUE TITLE
[M3] Iphigene's Task Reflections

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#60]
Each member is required to write no more than 2 paragraphs of what they have done for milestone one, what they have learned, how they were to do it differently if they are given another chance to do it again, and as a team what can be done better.

**Comment by Iphigene** [comment]
For milestone 3, I was in charge of black box testing and IT admin prototype. I also made changes to the sequence diagram and project management requirements from M2. Throughout this milestone, I learned how intensive each testing procedure can be as it requires careful consideration and attention to detail before deriving the specific test cases for the decision table, boundary value analysis and equivalent partitioning. 

If given a chance to do it again, I would choose to understand and clarify any doubts I have with various black box testing techniques such as the boundary value analysis and equivalent partitioning in advance. These techniques can be rather confusing if applied otherwise and without a complete understanding of its purpose. The project would be smoother and more manageable if the required team size of 4 was met, nonetheless the team tried our best to complete all milestones with limited resources/manpower.
